import { defineField, defineType } from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Lehe seaded',
  type: 'document',
  fields: [
    // ── HERO ──────────────────────────────────────────────
    defineField({
      name: 'heroHeadingLine1',
      title: 'Hero — pealkiri rida 1',
      type: 'string',
      initialValue: 'Sinu kinnisvara.',
      group: 'hero',
    }),
    defineField({
      name: 'heroHeadingLine2',
      title: 'Hero — pealkiri rida 2 (oranž)',
      type: 'string',
      initialValue: 'Minu prioriteet.',
      group: 'hero',
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Hero — alapealkiri',
      type: 'text',
      rows: 2,
      initialValue: 'Läbipaistev, aus ja detailidele orienteeritud maakler, kes paneb sinu eesmärgid alati esikohale.',
      group: 'hero',
    }),
    defineField({
      name: 'heroPrimaryButton',
      title: 'Hero — esmane nupp tekst',
      type: 'string',
      initialValue: 'Tasuta kinnisvara hinnastamine',
      group: 'hero',
    }),
    defineField({
      name: 'heroSecondaryButton',
      title: 'Hero — teisene nupp tekst',
      type: 'string',
      initialValue: 'Suundu minu portfelli',
      group: 'hero',
    }),
    defineField({
      name: 'heroPhoto',
      title: 'Hero — foto',
      type: 'image',
      options: { hotspot: true },
      group: 'hero',
    }),

    // ── HERO CHIPS ────────────────────────────────────────
    defineField({
      name: 'chip1Value',
      title: 'Chip 1 — number (nt "100+")',
      type: 'string',
      initialValue: '100+',
      group: 'hero',
    }),
    defineField({
      name: 'chip1Label',
      title: 'Chip 1 — tekst',
      type: 'string',
      initialValue: 'Klienti aidatud',
      group: 'hero',
    }),
    defineField({
      name: 'chip2Value',
      title: 'Chip 2 — number (nt "~65p")',
      type: 'string',
      initialValue: '~65p',
      group: 'hero',
    }),
    defineField({
      name: 'chip2Label',
      title: 'Chip 2 — tekst',
      type: 'string',
      initialValue: 'Keskmine tehinguaeg',
      group: 'hero',
    }),
    defineField({
      name: 'chip3Value',
      title: 'Chip 3 — number (nt "TOP 1")',
      type: 'string',
      initialValue: 'TOP 1',
      group: 'hero',
    }),
    defineField({
      name: 'chip3Label',
      title: 'Chip 3 — tekst',
      type: 'string',
      initialValue: 'Kodumaa käive 2025',
      group: 'hero',
    }),
    defineField({
      name: 'chip4Value',
      title: 'Chip 4 — number (nt "5+")',
      type: 'string',
      initialValue: '5+',
      group: 'hero',
    }),
    defineField({
      name: 'chip4Label',
      title: 'Chip 4 — tekst',
      type: 'string',
      initialValue: 'Aastat müügikogemust',
      group: 'hero',
    }),

    // ── ABOUT / MINUST ────────────────────────────────────
    defineField({
      name: 'aboutHeading',
      title: 'Minust — pealkiri',
      type: 'string',
      initialValue: 'Maakler, kes räägib Sulle alati tõtt.',
      group: 'about',
    }),
    defineField({
      name: 'aboutSubtitle',
      title: 'Minust — sissejuhatus',
      type: 'text',
      rows: 3,
      initialValue: 'Minu fookus ei ole minu enda edu — fookus on väärtusel, mida loon igale kliendile. Iga tehing on ainulaadne ning iga inimene vajab personaalset lähenemist.',
      group: 'about',
    }),
    defineField({
      name: 'aboutPhoto',
      title: 'Minust — foto',
      type: 'image',
      options: { hotspot: true },
      group: 'about',
    }),
    defineField({
      name: 'aboutQuote',
      title: 'Minust — tsitaat',
      type: 'string',
      initialValue: '"I\'m not important, but what I do and what I give is."',
      group: 'about',
    }),

    // ── CONTACT ───────────────────────────────────────────
    defineField({
      name: 'contactHeadingLine1',
      title: 'Kontakt — pealkiri rida 1',
      type: 'string',
      initialValue: 'Alusta oma',
      group: 'contact',
    }),
    defineField({
      name: 'contactHeadingLine2',
      title: 'Kontakt — pealkiri rida 2',
      type: 'string',
      initialValue: 'kinnisvara',
      group: 'contact',
    }),
    defineField({
      name: 'contactHeadingLine3',
      title: 'Kontakt — pealkiri rida 3',
      type: 'string',
      initialValue: 'teekonda.',
      group: 'contact',
    }),
    defineField({
      name: 'contactSubtitle',
      title: 'Kontakt — alapealkiri',
      type: 'text',
      rows: 2,
      initialValue: 'Olenemata sellest, kas oled ostja või müüja — olen siin, et aidata sul teha parim otsus.',
      group: 'contact',
    }),
    defineField({
      name: 'contactPhone',
      title: 'Kontakt — telefon',
      type: 'string',
      initialValue: '+372 5393 5292',
      group: 'contact',
    }),
    defineField({
      name: 'contactEmail',
      title: 'Kontakt — e-post',
      type: 'string',
      initialValue: 'Reno@kodumaakv.ee',
      group: 'contact',
    }),
    defineField({
      name: 'contactWhatsapp',
      title: 'Kontakt — WhatsApp link (nt https://wa.me/37253935292)',
      type: 'url',
      initialValue: 'https://wa.me/37253935292',
      group: 'contact',
    }),
    defineField({
      name: 'contactKvUrl',
      title: 'Kontakt — KV.EE profiili link',
      type: 'url',
      initialValue: 'https://www.kv.ee/broker/renomark',
      group: 'contact',
    }),
    defineField({
      name: 'ctaCardTitle',
      title: 'CTA kaart — pealkiri',
      type: 'string',
      initialValue: 'Valmis alustama?',
      group: 'contact',
    }),
    defineField({
      name: 'ctaCardSubtitle',
      title: 'CTA kaart — tekst',
      type: 'text',
      rows: 2,
      initialValue: 'Esimene konsultatsioon on alati tasuta. Räägi mulle oma soovidest ja vaatame koos, kuidas saan aidata.',
      group: 'contact',
    }),
    defineField({
      name: 'ctaBullets',
      title: 'CTA kaart — punktid',
      type: 'array',
      of: [{ type: 'string' }],
      initialValue: [
        'Tasuta esialgne konsultatsioon',
        'Kiire vastus — maksimaalselt 24h',
        'Personaalne lähenemine igale kliendile',
        'Läbipaistev protsess algusest lõpuni',
      ],
      group: 'contact',
    }),
    defineField({
      name: 'ctaPrimaryButton',
      title: 'CTA kaart — esmane nupp',
      type: 'string',
      initialValue: 'Helista kohe',
      group: 'contact',
    }),
    defineField({
      name: 'ctaSecondaryButton',
      title: 'CTA kaart — teisene nupp',
      type: 'string',
      initialValue: 'Kirjuta mulle',
      group: 'contact',
    }),
  ],
  groups: [
    { name: 'hero', title: 'Hero sektsioon' },
    { name: 'about', title: 'Minust sektsioon' },
    { name: 'contact', title: 'Kontakt sektsioon' },
  ],
  preview: {
    prepare() {
      return { title: 'Lehe seaded' }
    },
  },
})
